export const COMMUTE_KEY = {
    SET_ARRIVE: "SET_ARRIVE",
    SET_LEAVE: "SET_LEAVE",
    SET_AM_HOLIDAY: "SET_AM_HOLIDAY",
    SET_PM_HOLIDAY: "SET_PM_HOLIDAY",
    SET_ANNUAL_HOLIDAY: "SET_ANNUAL_HOLIDAY",
};
